[package]
name = "quiz_domain_mocks"
version = "0.1.0"
authors = ["Josh Jones <ohblonddev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "^0.8.1"
quiz_domain = { path="../quiz_domain" }
