[package]
name = "quiz_domain"
version = "0.1.0"
authors = ["Josh Jones <ohblonddev@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
mockall = "^0.8.1"
spectral = "^0.6.0"
